language: android

android:
  components:
    - platform-tools
    - tools
    - android-23
    - build-tools-23.0.2
    - extra-android-m2repository

jdk:
  - oraclejdk7

cache:
  directories:
    - $HOME/.gradle


deploy:
  provider: bintray
  file: "bintray.json"
  user: "dsokolov"
  key: $BINTRAY_API_KEY