language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.2
    - android-27
    - extra-android-m2repository

before_install:
  - yes | sdkmanager "platforms;android-27"

script:
    - ./gradlew clean
    - ./gradlew assembleRelease
    - ./gradlew uploadArchives
    - ./gradlew generateBintrayJson

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.gradle

deploy:
  provider: bintray
  file: "bintray.json"
  user: "dsokolov"
  key: $BINTRAY_API_KEY
